import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { getProgress } from "./Progress";
import PremiumPlans from "../components/PremiumPlans"; // ✅ IMPORT POPUP

// -------------------------------------------------------------
// PREMIUM PDF GENERATOR
// -------------------------------------------------------------
const generateCareerPDF = () => {
  const { jsPDF } = require("jspdf");
  const doc = new jsPDF("p", "mm", "a4");

  const stage5 = JSON.parse(localStorage.getItem("stage5to7Result")) || {
    title: "N/A",
    subjects: [],
    activities: [],
    description: "N/A",
  };

  const stage8 = JSON.parse(localStorage.getItem("stage8to10Result")) || {
    title: "N/A",
    careers: [],
    paths: [],
    description: "N/A",
  };

  const stage11 = JSON.parse(localStorage.getItem("stage11to12Result")) || {
    finalPath: "N/A",
    score: "N/A",
  };

  const progress = getProgress();

  // HEADER
  doc.setFillColor(63, 131, 248);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("CareerGenAI – Full Career Report", 15, 20);

  doc.setFontSize(13);
  doc.text("🎓 AI-Powered Student Career Assessment Summary", 15, 30);

  let y = 45;

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("✓ Completion Status", 15, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(`5th–7th: ${progress.stage5to7 ? "✔ Completed" : "❌ Pending"}`, 15, y);
  y += 7;
  doc.text(`8th–10th: ${progress.stage8to10 ? "✔ Completed" : "❌ Pending"}`, 15, y);
  y += 7;
  doc.text(`11th–12th: ${progress.stage11to12 ? "✔ Completed" : "❌ Pending"}`, 15, y);
  y += 15;

  // Section function...
  const addSection = (title, content) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(63, 131, 248);
    doc.text(title, 15, y);
    y += 8;

    doc.setDrawColor(200, 200, 200);
    doc.line(15, y, 195, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    const lines = doc.splitTextToSize(content, 180);
    doc.text(lines, 15, y);
    y += lines.length * 6 + 5;
  };

  // Stage blocks...
  if (progress.stage5to7) {
    addSection(
      "Stage 5th–7th Result",
      `
Personality Type: ${stage5.title}
Subjects Liked: ${stage5.subjects.join(", ") || "N/A"}
Activities: ${stage5.activities.join(", ") || "N/A"}
Description: ${stage5.description}
`
    );
  }

  if (progress.stage8to10) {
    addSection(
      "Stage 8th–10th Result",
      `
Career Stream: ${stage8.title}
Careers: ${stage8.careers.join(", ") || "N/A"}
Learning Path: ${stage8.paths.join(" → ") || "N/A"}
Description: ${stage8.description}
`
    );
  }

  if (progress.stage11to12) {
    addSection(
      "Stage 11th–12th Result",
      `
Final Path Recommendation: ${stage11.finalPath}
Score Achieved: ${stage11.score}
`
    );
  }

  // FOOTER
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120, 120, 120);
  doc.setFontSize(10);
  doc.text(
    "This report is auto-generated by CareerGenAI – AI-Driven Career Guidance System.",
    15,
    285
  );

  doc.save("CareerGenAI_Final_Report.pdf");
};

// -------------------------------------------------------------
// PAGE UI WITH PREMIUM LOCK
// -------------------------------------------------------------
export default function FinalReportPage() {
  const navigate = useNavigate();

  const isPremium = localStorage.getItem("isPremiumUser") === "true";

  const [showPremiumPopup, setShowPremiumPopup] = useState(false); // ✅ POPUP CONTROL

  const handleDownload = () => {
    if (!isPremium) {
      setShowPremiumPopup(true); // ✅ SHOW POPUP INSTEAD OF REDIRECT
      return;
    }
    generateCareerPDF();
  };

  return (
    <div className="min-h-screen flex justify-center items-center bg-blue-50 px-6">

      {/* 🔥 PREMIUM POPUP HERE */}
      {showPremiumPopup && (
        <PremiumPlans onClose={() => setShowPremiumPopup(false)} />
      )}

      <div className="bg-white p-10 rounded-3xl shadow-2xl border max-w-xl text-center">

        <h1 className="text-3xl font-bold text-blue-800 mb-4">
          🎉 Your Complete Career Journey Report
        </h1>

        <p className="text-gray-600 mb-6">
          Download your full AI-generated report (Premium feature).
        </p>

        {/* ---------- DOWNLOAD BUTTON ---------- */}
        <button
          onClick={handleDownload}
          className={`px-8 py-3 rounded-xl text-lg transition shadow-lg 
            ${isPremium ? "bg-blue-600 text-white hover:bg-blue-700" : "bg-yellow-500 text-white hover:bg-yellow-600"}`}
        >
          {isPremium ? "Download Full Report 📄" : "Upgrade to Download 🔒"}
        </button>

      </div>
    </div>
  );
}
